#!/bin/bash

CWD=$(dirname $BASH_SOURCE)
BIN="$CWD/../bin"
PATH=$CWD:$BIN:$PATH

echo ""
echo "===================================== Requirement 4 ====================================="
echo ""
echo "Write a program in C/C++, named “restore”, to recover the deleted file using P.bin and the"
echo "remaining three files from step 1. Please design the program arguments/options to take the"
echo "input and output files."
echo ""
echo "========================================================================================="
echo ""

echo "The 'restore' program will be available after using 'make' command to build this project,"
echo "or if you are on x86_64 system, it will use the pre-built binaries inside 'bin/' directory"
echo "but it's better to build it yourself because you might encounter shared library issues."
echo ""


echo "RUN: restore B.bin C.bin D.bin P.bin --verbose --output 'A.bin.restored'"
restore B.bin C.bin D.bin P.bin --verbose --output 'A.bin.restored'

echo ""
echo "Right now the 'A.bin.restored' has been generated, let's see if the content is the same"
echo "with the original file 'A.bin.original'!"
echo ""

echo "RUN: diff A.bin.original A.bin.restored"
echo "=========================  The output of the 'diff' command  ==========================="
echo ""
echo "IF THIS SECTION IS EMPTY MEANS THAT 'A.bin.original' IS THE SAME WITH 'A.bin.restored'!!!"
diff A.bin.original A.bin.restored
echo ""
echo "========================================================================================"
echo ""

sleep 3

read -p "Do you want to run 'clear-data.sh' to clear the file generated by the scripts? (y/n): " delete
if [ "$delete" == "y" ]; then
    clear-data.sh
else
    echo "You can still run 'clear-data.sh' later on!"
fi
