#!/bin/bash

CWD=$(dirname $BASH_SOURCE)
SRC="$CWD/../src"
PATH=$CWD:$SRC:$PATH

restore --verbose B.bin C.bin D.bin P.bin --output "A.bin.restored"

echo "=========================  DIFF A.bin.original A.bin.restored  ========================="
diff A.bin.original A.bin.restored
echo "========================================================================================"

read -p "Do you want to run `clear-data.sh` to clear the file generated by the scripts? (y/n): " delete
if [ "$delete" == "y" ]; then
    clear-data.sh
else
    echo "You can still run `clear-data.sh` later on!"
fi
